### ISSUE TITLE
Wrong mesh generated with hand data from your dataloader and camera pose

### ISSUE THREAD

**Issue by hongsiyu** [LinjieLyu/NRTF#1]
Your work is excellent! But I stuck in geometry training while reproducing your work. Following your instruction, I still get wrong mesh by using neurecon.

**Comment by LinjieLyu** [comment]
Hello @hongsiyu. Did you use neus.yaml in neurecon as the config? It runs the Neus-with-mask setting. Also, remember to normalize your scene, so the mesh is bounded in the unit sphere.

**Comment by hongsiyu** [comment]
> Hello @hongsiyu. Did you use neus.yaml in neurecon as the config? It runs the Neus-with-mask setting. And you should convert the hand data to the [DTU](https://github.com/lioryariv/idr/blob/main/data/download_data.sh) format before running neus, e.g. /image/0.exr to /image/000.png and /mask/0.png to /mask/000.png. In their code, they glob the filenames and you need padding to get the correct order.

According to your DTU.py, we can get correct order when images' names is the same as masks' names. And I reset the scale_radius = 1 in your DTU.py to normalize the camera poses, while using neus.yaml, I still get the wrong mesh. I visualized the wrong mesh in the meshlab and found the camera poses you provided may be incorrect. Could you check this camera poses.

**Comment by LinjieLyu** [comment]
I just ran neus with a couple of iterations using the released camera poses, and it looks like this.
![Screenshot 2022-09-07 121241](https://user-images.githubusercontent.com/65668654/188854722-1be5f027-bbe6-4fb2-aff4-20586eadc41f.png)
Just in case, I updated the released dataset to match the DTU convention and uploaded the example config. Could you try that again?

**Comment by hongsiyu** [comment]
> 
You are right, I am so sorry that I made a stupid mistake by sorting the files in wrong order which didn't match the camera pose correctly. And I get correct mesh now. Thanks for your help!

**Comment by LinjieLyu** [comment]
Glad you solve it!
