### ISSUE TITLE
what's the output of blender

### ISSUE THREAD

**Issue by brabbitdousha** [LinjieLyu/NRTF#10]
I opened the OLAT_example.blend,and changed the mesh,texture to diffuse/3000.exr,and I also set the alpha and weight...
However,I get render result like this eg. olat_data/cam1light10.exr
![image](https://user-images.githubusercontent.com/22854457/232224711-8ca6ee0c-0a01-4d8d-b4e3-09d2e8370578.png)

It doesn't look like what the gt should be.....

**Comment by brabbitdousha** [comment]
Sorry this is the blender issue! I am using the 3.5 version of blender...
I changed to version 2.93..
and It looks like this
![image](https://user-images.githubusercontent.com/22854457/232226771-bccae025-5e50-4a74-bd2b-23d1e872974f.png)
I wish it's right...Is it what supposed to be?

**Comment by LinjieLyu** [comment]
Hi @brabbitdousha. Sorry for the late reply. This image looks like an OLAT, though I can't tell if the material is correctly estimated. But I guess if the blender material type is matched with Mitsuba2 and the material estimation goes well, there should be no problems.
