### ISSUE TITLE
train_joint.py rgb_loss only for a chunk of pixels

### ISSUE THREAD

**Issue by EliaFantini** [LinjieLyu/NRTF#3]
This is not really an issue, but I was wondering why in train_joint.py the rgb_loss is calculated only on 3000 random pixels whereas olat_loss is calculated on all of them? Also, how is the envmap getting updated if the two optimizers only received as variables to optimize the PRTNetwork and the hashembedder?

**Comment by LinjieLyu** [comment]
Hi. It means in train_joint.py, the batch size of rays is 3000, for the sake of memory trade-off. I updated the train_joint.py and added an argument for batch size. 
As for the envmap optimization, I did miss the envmap optimizer when I was rewriting the code, which is added now. Thanks for pointing it out.
