### ISSUE TITLE
Training joint use less GPU memory

### ISSUE THREAD

**Issue by hongsiyu** [LinjieLyu/NRTF#4]
I finish all the step except train joint optimization in RTX6000. This step need more GPU memory and out of 24GB. Though I reduce the sample number but still fail in training. Could you tell which param should I change in the file?

**Comment by LinjieLyu** [comment]
Hello. I added an argument for the batch size of rays in train_joint.py. The default is around 3000. You can decrease the batch size if you face a memory issue.

**Comment by hongsiyu** [comment]
> Hello. I added an argument for the batch size of rays in train_joint.py. The default is around 3000. You can decrease the batch size if you face a memory issue.

I saw your code where you changed, I have decrease this param before asking this question.  Even I decreased it to 100, I still met memory issue.
