### ISSUE TITLE
NO jobid NRTF/blender/OLAT_synthesis.py", line 13

### ISSUE THREAD

**Issue by colin-de** [LinjieLyu/NRTF#6]
```(p3dcv) hyunjun@atnavab51:/media/hyunjun/NewDisk/p3dcv_2022/NRTF/blender$ ../../lib/blender-3.3.1-linux-x64/blender OLAT_example.blend  --background --python OLAT_synthesis.py
Blender 3.3.1 (hash b292cfe5a936 built 2022-10-05 00:14:35)
Read blend: /media/hyunjun/NewDisk/p3dcv_2022/NRTF/blender/OLAT_example.blend
Error: Python: Traceback (most recent call last):
  File "/media/hyunjun/NewDisk/p3dcv_2022/NRTF/blender/OLAT_synthesis.py", line 13, in <module>
    index=int(jobid)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
blah blah
Blender quit
```

Dear author, thanks for sharing your great works. However, I ran into the problem of not getting the jobid when running the file `OLAT_synthesis.py`. 
```sys.stderr.write("blah blah")
C = bpy.context
scn = C.scene

jobid = os.getenv('SLURM_ARRAY_TASK_ID')
```

I'm also a bit confused about it, could you please help me and give some suggestions? Thanks!

**Comment by LinjieLyu** [comment]
Hello, as said in [OLAT synthesis](https://github.com/LinjieLyu/NRTF/tree/main/blender), you may need a dense CPU or GPU cluster for parallel rendering. We give an example of how the script is running on multiple CPUs at the same time with  [slurm](https://slurm.schedmd.com/). You can customize the script according to your cluster system.
