### ISSUE TITLE
Where Do the NPZ's Come From?

### ISSUE THREAD

**Issue by MikePelton** [LinjieLyu/NRTF#8]
Hi - not so much an issue as a question. I see the DTU data is supplied with cameras.npz in one format, and you use another, and I see your code that turns a Blender scene into a "your format" npz. So have you gone from the original npz camera to Blender format somehow, or did you create a new set of camera poses (etc.) in Blender, and if the latter, was that via Colmap or some other route? This isn't in any way blocking me - am just curious!

**Comment by LinjieLyu** [comment]
Hi there. For the DTU dataset, I used the camera matrix decomposition in OpenCV to compute the intrinsic and extrinsic camera matrix, as what [IDR](https://github.com/lioryariv/idr) does [here](https://github.com/lioryariv/idr/blob/main/code/datasets/scene_dataset.py), and input them to Blender. Of course, one can always use Colmap or other pre-process to estimate the camera poses.

**Comment by MikePelton** [comment]
All good - thanks for coming back so quickly. Many thanks too for this code - phenomenal results!
